# this is a config for soc generator.

title = "SoC Inst Name"

[core]
name = "ysyx_xxxxxx"

[rcg]
pll_num = 2

[bus]
mst_num = 2
slv_num = 3

[ip]

# tag and commit field is optional
[ip.spi]
repo = "ysyxIP"
branch = "main"
tag = 0.02
commit = "bd8511"
[ip.uart]
repo = "ysyxIP"
branch = "main"
tag = 0.05
commit = "fb6f01"