../perip/spi/rtl/spi_clgen.v
../perip/spi/rtl/spi_defines.v
../perip/spi/rtl/spi_flash.v
../perip/spi/rtl/spi_shift.v
../perip/spi/rtl/spi_top.v
../perip/spiFlash/N25Q128A13E_VG12/code/N25Qxxx.v
../perip/uart/rtl/uart16550/raminfr.v
../perip/uart/rtl/uart16550/timescale.v
../perip/uart/rtl/uart16550/uart_defines.v
../perip/uart/rtl/uart16550/uart_receiver.v
../perip/uart/rtl/uart16550/uart_regs.v
../perip/uart/rtl/uart16550/uart_rfifo.v
../perip/uart/rtl/uart16550/uart_sync_flops.v
../perip/uart/rtl/uart16550/uart_tfifo.v
../perip/uart/rtl/uart16550/uart_transmitter.v
../perip/uart/rtl/uart_apb.v
../perip/uart/tb/tty.v
../perip/chiplink/simmem.v
../perip/chiplink/top.v
../perip/chiplink/chiplink.v
